# This is a basic workflow to help you get started with Actions

name: CI

env:
  iAmCamel: 'IaMcAMEL'

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          
      - name: Run hello world
        run: sudo docker run hello-world
