# This is a basic workflow to help you get started with Actions

name: Playground

on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - name: display
        run: ./0.2.9-preview2/Build.ps1
        shell: powershell