# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - name: display
        run: |-
          Write-Output "run_id ${{ github.run_id }}"
          Write-Output "run_number ${{ github.run_number }}"
