# This is a basic workflow to help you get started with Actions

name: Playground

on:
  workflow_dispatch:

jobs:
  playground:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: helloWorld
        shell: bash
        run: command -v pwsh
      - name: helloWorld
        shell: pwsh
        run: command -v pwsh
