# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - name: set
        id: set
        run: |-
          echo "::set-output name=CMD::Hi"
          pwsh -Command "Write-Output '::set-output name=PWSH::Hello'"
        shell: cmd

      - name: display
        run: |-
          Write-Output "cmd output is ${{ steps.set.outputs.CMD }}"
          Write-Output "pwsh output is ${{ steps.set.outputs.PWSH }}"
