# This is a basic workflow to help you get started with Actions

name: Playground

on:
  workflow_dispatch:

jobs:
  playground:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: helloWorld
        shell: bash
        run: printenv
  playground-windows:
    environment: test
    runs-on: windows-latest
    steps:
      - name: helloWorld
        shell: pwsh
        run: |
          dir env:
