# This is a basic workflow to help you get started with Actions

name: CI

env:
  iAmCamel: 'IaMcAMEL'

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: printenv
  
  windows:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        shell: pwsh
        run: "dir env:"
