# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - name: display
        run: |-
          Write-Host "::error::Missing semicolon"
