# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: windows-latest
    steps:
      - name: output
        run: |-
          echo "::set-output name=CMD::Hi"
          pwsh -Command 'Write-Output "::set-output name=PWSH::Hello"'
        shell: cmd
          
      - name: display
        run: |-
          Write-Output "cmd output is ${{ steps.output.outputs.CMD }}"
          Write-Output "pwsh output is ${{ steps.output.outputs.PWSH }}"
