# This is a basic workflow to help you get started with Actions

name: Playground

on:
  workflow_dispatch:

jobs:
  playground:
    environment: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: helloWorld
        run: echo helloWorld
