# This is a basic workflow to help you get started with Actions

name: Actions Windows

on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - name: display
        run: |-
          dir env:
          Write-Output "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon%0Afoo%0Abar"
