name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test1
      run: echo "test1" > ./test.txt
      
    - uses: actions/upload-artifact@v2
      with:
        name: hello
        path: ./test.txt
    
    - name: test2
      run: echo "test2" > ./test.txt
    
    - uses: actions/upload-artifact@v2
      with:
        name: hello
        path: ./test.txt
    
    - name: pwsh
      shell: pwsh
      run: echo '${{ github.ref_name }}'
