name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: pwsh
      shell: pwsh
      run: echo '${{ github.ref_name }}'

    - name: pwsh
      shell: pwsh
      run: printenv
