name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'OIDC login'
      uses: azure/login@v1
      with:
        client-id: ed91d9d8-a71d-4b0c-b4a4-64ae79005d7b
        tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
        subscription-id: 8a53cb9a-a3a5-4602-aa2d-8c171edde3c7
    - name: 'Run az commands'
      run: |
        az account show
        az group list
